version: '3'
services:
  redis:
    image: redis
    restart: always
    container_name: 'redis'
    command: redis-server
    ports:
      - '6379:6379'
  web:
    build: .
    restart: always
    container_name: 'traker'
    command:
      - python manage.py runserver 127.0.0.1:8000
      - python manage.py runbot
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    ports:
      - '8000:8000'
    env_file:
      - ./.env
  celery:
    build: .
    container_name: 'celery'
    command: celery -A traker worker -B
    links:
      - redis
    depends_on:
      - web
      - redis
volumes:
  static_value:
  media_value: