version: '3.3'
services:
  db:
    image: postgres:12.4
    container_name: 'database'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  redis:
    networks:
      - traker-network
    image: redis
    restart: always
    container_name: 'redis'
    command: redis-server
    ports:
      - '6379:6379'
  web:
    build: .
    restart: always
    container_name: 'traker'
    command: gunicorn traker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - ./.env
  bot:
    build: .
    restart: always
    container_name: 'bot'
    command: python manage.py runbot
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.3
    container_name: 'nginx_server'
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
  celery:
    build: .
    container_name: 'celery'
    command: celery -A traker worker -l info
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - web
      - redis
  celery-beat:
    build: .
    container_name: 'celery-beat'
    command: celery -A traker beat -l info
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - web
      - redis
networks:
  traker-network:
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "172.21.0.1"
    ipam:
      config:
        - subnet: "172.21.0.0/16"
volumes:
  static_value:
  media_value:
  postgres_data: