# Generated by Django 3.2.3 on 2021-07-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Пункт отчета', verbose_name='Текст репорта')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('author', models.PositiveIntegerField(verbose_name='Автор репорта')),
                ('status', models.CharField(choices=[('Normal', 'Normal'), ('Closed', 'Closed'), ('Urgent', 'Urgent'), ('Forgotten', 'Forgotten')], default='Normal', max_length=12, verbose_name='Status')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
