# Generated by Django 3.2.3 on 2021-08-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobinetreport',
            name='last_edit',
            field=models.DateTimeField(null=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AddField(
            model_name='moneyback',
            name='last_edit',
            field=models.DateTimeField(null=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AddField(
            model_name='report',
            name='last_edit',
            field=models.DateTimeField(null=True, verbose_name='Дата последнего изменения'),
        ),
    ]
