# Generated by Django 3.2.3 on 2021-07-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20210706_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Closed', 'Closed'), ('Urgent', 'Urgent'), ('Forgotten', 'Forgotten')], default='Normal', max_length=12, verbose_name='Статус'),
        ),
    ]
