# Generated by Django 3.2.3 on 2021-07-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20210719_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tag',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Burning', 'Burning'), ('Forgotten', 'Forgotten'), ('Delayed', 'Delayed')], default='Normal', max_length=12, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Closed', 'Closed'), ('Actual', 'Actual')], default='New', max_length=12, verbose_name='Статус'),
        ),
    ]
