# Generated by Django 3.2.3 on 2021-09-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20210818_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyback',
            name='wallet',
            field=models.CharField(max_length=50, verbose_name='Кошелек получателя'),
        ),
    ]
