# Generated by Django 3.2.3 on 2021-09-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_moneyback_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyback',
            name='payment_system',
            field=models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Ethereum', 'Ethereum'), ('WebMoney', 'Webmoney'), ('Qiwi', 'Qiwi')], default='Bitcoin', max_length=20, verbose_name='Платежная система'),
        ),
    ]
