# Generated by Django 3.2.3 on 2021-07-28 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20210720_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobinetReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.report')),
            ],
            options={
                'verbose_name': 'Отчет MN',
                'verbose_name_plural': 'Отчеты MN',
            },
            bases=('reports.report',),
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-date'], 'verbose_name': 'Отчет RS', 'verbose_name_plural': 'Отчеты RS'},
        ),
    ]
