# Generated by Django 3.2.3 on 2021-09-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_moneyback_payment_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyback',
            name='payment_system',
            field=models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Ethereum', 'Ethereum'), ('WebMoney', 'Webmoney'), ('Qiwi', 'Qiwi'), ('Card', 'Creditcard'), ('Other', 'Other')], default='Bitcoin', max_length=20, verbose_name='Платежная система'),
        ),
    ]
